# Generated by Django 5.2.7 on 2025-10-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='launch_data',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
