# Generated by Django 5.2.7 on 2025-10-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_menu_launch_data_alter_menu_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='launch_data',
            new_name='launch_date',
        ),
    ]
