services:
  vote_api:
    build:
      context: .
    command: bash -c "
      python /app/company/manage.py migrate
      && python /app/company/manage.py runserver 0.0.0.0:8000"
    container_name: vote_api
    ports:
      - "8000:8000"
    depends_on:
      django_db:
        condition: service_healthy

  django_db:
    image: "postgres:17.5-alpine"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  pgdbdata: null