# line-length = 120

[lint]
select = ["ALL"]

[lint.isort]
# For treating the 'base' package from my app as first-party package
# for the proper import sorting.
known-first-party = ["base"]

[lint.per-file-ignores]
# Here you can find what these codes are stand for
# https://docs.astral.sh/ruff/rules/
"company/api/tests/*" = ["ANN201", "ANN001", "ARG001", "S101", "D", "INP001"]